#!/usr/bin/env pwsh

cargo r -q -- deps dirname pwd
if ($LastExitCode -ne 0) {
  exit 1
}

$config = "$($ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath('.\'))/../complete.yml"
$code = $(cat $config `
    | cargo r -q -- parse pwsh _ -- $args `
    | Out-String)
if ([string]::IsNullOrWhiteSpace($code)) {
    Exit 1
}
Invoke-Expression $code
if ([string]::IsNullOrWhiteSpace($_success)) {
    Exit 1
}

Write-Output `
"opt     = '$_opt_vals'
pos     = '$_pos_vals'
flag    = '$_flag_vals'
mode    = '$_mode_vals'
mvals   = '$_mvals_vals'
minvals = '$_minvals_vals'
maxvals = '$_maxvals_vals'

subcommand   -> '$_subcommand'
subcmd_scopt  = '$_subcmd_scopt_vals'
subcmd_scpos1 = '$_subcmd_scpos1_vals'"

