#!/usr/bin/env bash
# shellcheck disable=SC2154

cargo r -q -- deps rg xargs sed || exit 1

eval "$(cargo r -q -- parse bash _ -- "$@" <<-EOF
name: sub
version: "1.0"
author: Matteo G. <matteoguarda@tutanota.com>
about: Searches for a pattern using ripgrep and substitutes all occurrences with a string.

settings:
    - ArgRequiredElseHelp
    - ColoredHelp
    - ColorAuto

args:
    - pattern:
        help: the pattern to search for
        required: true
    - substitute:
        help: the text to substitute the matches with
        required: true
    - dry_run:
        help: instead of modifying the files right away it shows you a preview of the changes
        short: d
        long: dry-run
EOF
)"; [[ -z "${_success}" ]] && exit 1

if [[ -n "${_dry_run_occurs}" ]]; then
    rg "${_pattern_vals}" | sed "s/${_pattern_vals}/${_substitute_vals}/g"
else
    rg "${_pattern_vals}" --files-with-matches \
        | xargs sed -i "s/${_pattern_vals}/${_substitute_vals}/g"
fi

