#!/usr/bin/env zsh

cargo r -q -- deps fd ffprobe paste bc || exit 1

eval "$(cargo r -q -- parse zsh _ -- "$@" <<-EOF
name: vlen
version: "1.0"
author: Matteo G. <matteoguarda@tutanota.com>
about: Searches for all videos starting from a given directory and outputs the cumulative duration.

settings:
    - ArgRequiredElseHelp
    - ColoredHelp
    - ColorAuto

args:
    - dir:
        help: the dir where to start searching from
        default_value: .
EOF
)"; [[ -z "${_success}" ]] && exit 1

fd "${_dir_vals}" -e mkv -e mp4 -e webm -x \
    ffprobe -v quiet -of csv=p=0 -show_entries format=duration {} \; \
    | paste -sd+ - \
    | bc

